Team members:
* Member 1: **Mathias**
* Member 2: **Ahonon Gobi Parfait**

# Série 1
Ce document contient les différents exercices à réaliser. Veuillez compléter et rendre ces exercices pour la semaine prochaine.

Pour chaque exercice:
* implémentez ce qui est demandé
* commentez votre code
* expliquez **en français** ce que vous avez codé dans la cellule correspondante

Dans vos explications à chacun des exercices, indiquez un pourcentage subjectif d'investissement de chaque membre du groupe. **Des interrogations aléatoires en classe pourront être réalisées pour vérifier votre contribution/compréhension.**

## Exercice 1
Le PGCD (plus grand commun diviseur) est le plus grand nombre entier qui divise simultanément deux autres nombres entiers.

Implémentez l'algorithme d'Euclide permettant de calculer le PGCD de deux nombres entiers. Vous trouverez plus d'informations concernant l'algorithme d'Euclide en cliquant sur ce [lien](https://en.wikipedia.org/wiki/Greatest_common_divisor#Euclid's_algorithm).

In [9]:
def gcd(n: int, m: int):
    result = 0
    while m != 0:
        n, m = m, n%m # n = m, m = n%m so we can get the remainder of the division of n by m
        result = n # the gcd is the last value of n
    return result

In [10]:
assert gcd(9,6) == 3
assert gcd(24,32) == 8
assert gcd(18,18) == 18
assert not gcd(10,15) == 10
assert not gcd(12,9) == 4
assert not gcd(14,14) == 34

### Explications

L'algorithme d'Euclide est un algorithme permettant de calculer le PGCD de deux nombres entiers. Il repose sur le fait que le PGCD de deux nombres est égal au PGCD du plus petit des deux nombres et du reste de la division du plus grand par le plus petit. On répète cette opération jusqu'à ce que le reste soit égal à 0. Le PGCD est alors le dernier reste non nul.

Donc, dans le code nous avons une boucle while qui s'arrête lorsque m est égal à 0. Dans cette boucle, on échange les valeurs de n et m et on affecte à n le reste de la division de n par m. Une fois la boucle terminée, on affecte à result la valeur de n qui est le PGCD des deux nombres.

## Exercice 2
Implémentez une manière de calculer $x^n$ en utilisant la méthode de dichotomie.

In [11]:
def powdi(x: int, n: int):
    if n== 0:
        return  1 # Cas de base : x^0 = 1
    if n % 2 == 0:
        return (x*x) ** (n//2) # Si n est pair, x^n = (x^2)^(n/2)
    else:
        return x * (x*x) ** (n//2) # Si n est impair, x^n = x * (x^2)^(n/2)
powdi(2,3)

8

In [12]:
assert powdi(2,3) == 8
assert powdi(4,2) == 16
assert powdi(2,2) == 4
assert powdi(4,0) == 1
assert powdi(2,1) == 2
assert not powdi(5,2) == 10
assert not powdi(3,7) == 10
assert not powdi(3,3) == 10

### Explications

1. Si $n=0$, on retourne 1 car $x^0 = 1$.
2. Si $n$ est pair, on retourne $(x^2)^{n/2}$.
3. Si $n$ est impair, on retourne $x * (x^2)^{n/2}$.
4. On répète les étapes 2 et 3 jusqu'à ce que $n=0$.
5. On retourne le résultat.

## Exercice 3
La suite de Fibonacci est une suite de nombres entiers dans laquelle chaque nombre $f_{n+2}$ correspond à la somme des deux nombres qui le précèdent, $f_{n+1}+f_{n}$.

Implémentez l'algorithme de Fibonacci en utilisant la multiplication matricielle.

## Our implementation:

In [15]:
def fibo(n: int):
    result = 0
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        A = [[1, 1], [1, 0]]
        B = [[1], [0]]
        for i in range(2, n+1):
            C = [[0], [0]]
            for j in range(2):
                for k in range(2):
                    C[j][0] += A[j][k] * B[k][0]
            B = C
        result = B[0][0]

    return result
fibo(8)

21

In [6]:
import numpy as np

def fibo(n: int):
    f0f1 = np.array([[0],[1]])
    # A COMPLETER
    A = np.array([[0,1],
                  [1,1]])
    Apower_n = np.linalg.matrix_power(A, n) # utiliser powdi est preferable !!!
    print(Apower_n)
    return (Apower_n @ f0f1)[0]

In [8]:
fibo(9)

[[21 34]
 [34 55]]


array([34])

In [13]:
def powdi(x: int, n: int):
    # A COMPLETER
    if n == 0:
        return np.identity(2)
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n/2) @ powdi(x, n/2)
    if n % 2 != 0:
        return x @ powdi(x, n//2) @ powdi(x, n//2)
    return None

In [14]:
powdi(np.array([[0,1],[1,1]]), 8)

array([[13, 21],
       [21, 34]])

In [ ]:
assert fibo(8) == 21
assert fibo(10) == 55
assert fibo(0) == 0
assert fibo(1) == 1
assert not fibo(5) == 10

[[13 21]
 [21 34]]
[[34 55]
 [55 89]]
[[1 0]
 [0 1]]
[[0 1]
 [1 1]]
[[3 5]
 [5 8]]


### Explications

L'algorithme de Fibonacci en utilisant la multiplication matricielle repose sur le fait que la suite de Fibonacci peut être représentée par une matrice $A$ telle que $\left[\begin{array}{c}
f_{n+1} \\
f_{n}
\end{array}\right] = A \left[\begin{array}{c} f_{n} \\ f_{n-1} \end{array}\right]$. On peut alors calculer $f_n$ en multipliant $A$ par $\left[\begin{array}{c} f_{n-1} \\ f_{n-2} \end{array}\right]$ et en répétant l'opération jusqu'à $n$. 

Illustration de la méthode pour $n=4$:
* $f_4 = f_3 + f_2$
* $f_3 = f_2 + f_1$
* $f_2 = f_1 + f_0$
* $f_1 = f_0 + f_{-1}$
* $f_0 = 0$
* $f_{-1} = 0$
* $f_1 = 1$
* $f_2 = 1$
* $f_3 = 2$
* $f_4 = 3$

On peut alors représenter les équations par une matrice $A = \left[\begin{array}{cc} 1 & 1 \\ 1 & 0 \end{array}\right]$ et $B = \left[\begin{array}{c} f_{n+1} \\ f_{n} \end{array}\right]$. On peut alors calculer $f_n$ en multipliant $A$ par $B$ et en répétant l'opération jusqu'à $n$.



Voyons les étapes avec un cas spécifique, comme `fibo(4)` :

### Cas de `fibo(4)` : 

#### Initialisation :
- $n = 4$
- Le vecteur $B$ est initialisé comme $\begin{pmatrix} 1 \\ 0 \end{pmatrix}$, ce qui correspond à $f_1 = 1$ et $f_0 = 0$.
- La matrice $A$ est $\begin{pmatrix} 1 & 1 \\ 1 & 0 \end{pmatrix}$, qui est la matrice de transformation utilisée pour la suite de Fibonacci.

#### Itérations dans la boucle `for` :
1. **Itération 1 ($i = 2$)** :
   - On calcule $C = A \times B$ :
     $\[
     C[0][0] = A[0][0] \times B[0][0] + A[0][1] \times B[1][0] = 1 \times 1 + 1 \times 0 = 1
     \]$
     $\[
     C[1][0] = A[1][0] \times B[0][0] + A[1][1] \times B[1][0] = 1 \times 1 + 0 \times 0 = 1
     \]$
   - Le vecteur $C$ devient $\begin{pmatrix} 1 \\ 1 \end{pmatrix}$, ce qui correspond à $f_2 = 1$.

2. **Itération 2 ($i = 3$)** :
   - On calcule $C = A \times B$ :
     $\[
     C[0][0] = A[0][0] \times B[0][0] + A[0][1] \times B[1][0] = 1 \times 1 + 1 \times 1 = 2
     \]$
     $\[
     C[1][0] = A[1][0] \times B[0][0] + A[1][1] \times B[1][0] = 1 \times 1 + 0 \times 1 = 1
     \]$
   - Le vecteur $C$ devient $\begin{pmatrix} 2 \\ 1 \end{pmatrix}$, ce qui correspond à $f_3 = 2$.

3. **Itération 3 ($i = 4$)** :
   - On calcule $C = A \times B$ :
     $\[
     C[0][0] = A[0][0] \times B[0][0] + A[0][1] \times B[1][0] = 1 \times 2 + 1 \times 1 = 3
     \]$
    $\[
     C[1][0] = A[1][0] \times B[0][0] + A[1][1] \times B[1][0] = 1 \times 2 + 0 \times 1 = 2
     \]$
   - Le vecteur $C$ devient $\begin{pmatrix} 3 \\ 2 \end{pmatrix}$, ce qui correspond à $f_4 = 3$.

#### Résultat final :
- Après la dernière itération, $B[0][0] = 3$ est le 4ème nombre de Fibonacci.


### Exercice 3.1
$(1)$ Montrez qu'il existe une matrice $A$ reliant $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ à $\left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$ pour tout $n\in \mathbb{N}$.

$(2)$ Trouvez alors une expression de $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ selon $A$ et  $\left[\begin{array}{c}
f_0 \\
f_{1}
\end{array}\right]$ .

### Exercice 3.1

$(1)$ Démontrez qu'il existe une matrice $A$ reliant 
$$
\begin{pmatrix}
f_n \\
f_{n+1}
\end{pmatrix}
$$
à 
$$
\begin{pmatrix}
f_{n+1} \\
f_{n+2}
\end{pmatrix}
$$
pour tout $n \in \mathbb{N}$.

**Solution :** 

Nous savons que la suite de Fibonacci est définie par la relation de récurrence :
$$
f_{n+2} = f_{n+1} + f_n
$$
Cela signifie que nous pouvons exprimer le vecteur 
$$
\begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}
$$
comme une combinaison linéaire du vecteur 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
à l'aide de la matrice suivante :
$$
A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
$$
En effet, en appliquant cette matrice à 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
nous obtenons :
$$
A \cdot \begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix} = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix} \cdot \begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix} = \begin{pmatrix} f_{n+1} \\ f_n + f_{n+1} \end{pmatrix} = \begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}
$$

Cela prouve qu'il existe bien une matrice $A$ reliant 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
à 
$$
\begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}
$$
pour tout $n \in \mathbb{N}$.

$(2)$ Exprimez alors 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
selon $A$ et 
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix}.
$$

**Solution :** 

Nous savons que la matrice $A$ permet de relier deux vecteurs consécutifs de la suite de Fibonacci. Par conséquent, pour exprimer 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
en fonction de 
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix}
$$
il suffit de multiplier la matrice $A$ de manière itérative $n$ fois :
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix} = A^n \cdot \begin{pmatrix} f_0 \\ f_1 \end{pmatrix}
$$
où
$$
A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
$$
et
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$$

Ainsi, pour un entier $n$, nous pouvons obtenir le vecteur 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
en appliquant $A^n$ au vecteur initial 
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix}
$$


### Exercice 3.2 - (<font color='#db60cf'>Bonus</font>) Une formule analytique pour $f_n$
Que peut-on dire de $A$ ? Déterminez ses valeurs propres et ses sous-espaces propres associés.

<< A REMPLIR PAR L'ETUDIANT >>

En utilisant $(2)$, en déduire une forme analytique de $f_n$.

<< A REMPLIR PAR L'ETUDIANT >>

## Exercice 4
Implémentez et testez les 3 versions de l'algorithme calculant la sous-suite de somme maximale, c'est-à-dire:
* 3 boucles imbriquées
* 2 boucles imbriquées
* une seule boucle (Kadane)

In [25]:
def maxSub3(m):
    maxSum = 0 # initialiser la somme maximale à 0
    n = len(m) # obtenir la taille de la liste
    for i in range(n): # parcourir la liste
        for j in range(i, n): # parcourir la liste à partir de l'indice i
            currentSum = 0 # initialiser la somme courante à 0
            for k in range(i, j+1): # parcourir la liste de i à j
                currentSum += m[k] # ajouter l'élément k à la somme courante
            maxSum = max(maxSum, currentSum) # mettre à jour la somme maximale
    return maxSum

def maxSub2(m):
    maxSum = 0
    n = len(m)
    for i in range(n): 
        currentSum = 0
        for j in range(i, n):
            currentSum += m[j]
            maxSum = max(maxSum, currentSum)
    return maxSum

def maxSub1(m):
    maxSum = 0
    currentSum = 0

    for x in m:  # Boucle unique pour parcourir les éléments
        currentSum = max(x, currentSum + x)
        maxSum = max(maxSum, currentSum)
    return maxSum

7

In [26]:
assert maxSub3([4,3,-10,2]) == 7
assert maxSub3([4,3,-10,2,8]) == 10
assert not maxSub3([4,3,-10,2,8]) == -10

assert maxSub2([4,3,-10,2]) == 7
assert maxSub2([4,3,-10,2,8]) == 10
assert not maxSub2([4,3,-10,2,8]) == -10

assert maxSub1([4,3,-10,2]) == 7
assert maxSub1([4,3,-10,2,8]) == 10
assert not maxSub1([4,3,-10,2,8]) == -10

### Explications

1. **`maxSub3(m)`** :
   - Utilise trois boucles imbriquées. La somme des sous-suites est calculée avec une boucle interne, en ajoutant chaque élément de la sous-suite à `currentSum`. Ensuite, `maxSum` est mis à jour si `currentSum` est plus grand.

2. **`maxSub2(m)`** :
   - Utilise deux boucles imbriquées. La première boucle fixe le début de la sous-suite. La seconde boucle calcule la somme de la sous-suite en ajoutant successivement les éléments. `maxSum` est mis à jour pour chaque sous-suite.

3. **`maxSub1(m)`** :
   - Utilise l'algorithme de Kadane avec une seule boucle. La variable `currentSum` maintient la somme de la sous-suite courante, et `maxSum` est mis à jour si `currentSum` est plus grand.

Prenons l'exemple `[-1, 2, 5, 1]`.

L'objectif est de trouver la sous-séquence (une série d'éléments consécutifs dans la liste) qui a la somme maximale. Voici comment ça marche avec trois boucles imbriquées :

### Tableau : `[-1, 2, 5, 1]`

1. **Boucle externe (i)** : Sélectionne le point de départ de la sous-séquence.
2. **Boucle intermédiaire (j)** : Sélectionne le point de fin de la sous-séquence.
3. **Boucle interne (k)** : Calcule la somme de tous les éléments entre les indices \( i \) et \( j \).

### Étape par étape :

1. **i = 0 (on commence au premier élément -1)** :
    - j = 0 → sous-séquence : `[-1]` → somme = -1
    - j = 1 → sous-séquence : `[-1, 2]` → somme = 1
    - j = 2 → sous-séquence : `[-1, 2, 5]` → somme = 6
    - j = 3 → sous-séquence : `[-1, 2, 5, 1]` → somme = 7 (nouveau max)

2. **i = 1 (on commence au deuxième élément 2)** :
    - j = 1 → sous-séquence : `[2]` → somme = 2
    - j = 2 → sous-séquence : `[2, 5]` → somme = 7 (max reste 7)
    - j = 3 → sous-séquence : `[2, 5, 1]` → somme = 8 (nouveau max)

3. **i = 2 (on commence au troisième élément 5)** :
    - j = 2 → sous-séquence : `[5]` → somme = 5
    - j = 3 → sous-séquence : `[5, 1]` → somme = 6

4. **i = 3 (on commence au dernier élément 1)** :
    - j = 3 → sous-séquence : `[1]` → somme = 1

### Conclusion :

Le maxSum final est 8, qui correspond à la sous-séquence `[2, 5, 1]`.