Team members (JMCS):
* Member 1: **Pelissier Mathias**
* Member 2: **Ahonon Gobi Parfait**

# Série 1
Ce document contient les différents exercices à réaliser. Veuillez compléter et rendre ces exercices pour la semaine prochaine.

Pour chaque exercice:
* implémentez ce qui est demandé
* commentez votre code
* expliquez **en français** ce que vous avez codé dans la cellule correspondante

Dans vos explications à chacun des exercices, indiquez un pourcentage subjectif d'investissement de chaque membre du groupe. **Des interrogations aléatoires en classe pourront être réalisées pour vérifier votre contribution/compréhension.**

## Exercice 1
Le PGCD (plus grand commun diviseur) est le plus grand nombre entier qui divise simultanément deux autres nombres entiers.

Implémentez l'algorithme d'Euclide permettant de calculer le PGCD de deux nombres entiers. Vous trouverez plus d'informations concernant l'algorithme d'Euclide en cliquant sur ce [lien](https://en.wikipedia.org/wiki/Greatest_common_divisor#Euclid's_algorithm).

In [ ]:
def gcd(n: int, m: int):
    result = 0
    # A COMPLETER
    while m != 0:
        n, m = m, n%m
        #          ^-- modulo operator!
        result = n
    return result

In [2]:
assert gcd(9,6) == 3
assert gcd(24,32) == 8
assert gcd(18,18) == 18
assert not gcd(10,15) == 10
assert not gcd(12,9) == 4
assert not gcd(14,14) == 34

### Explications (100% Gobi)

L'algorithme d'Euclide est un algorithme permettant de calculer le PGCD de deux nombres entiers. Il repose sur le fait que le PGCD de deux nombres est égal au PGCD du plus petit des deux nombres et du reste de la division du plus grand par le plus petit. On répète cette opération jusqu'à ce que le reste soit égal à 0. Le PGCD est alors le dernier reste non nul.

Donc, dans le code nous avons une boucle while qui s'arrête lorsque m est égal à 0. Dans cette boucle, on échange les valeurs de n et m et on affecte à n le reste de la division de n par m. Une fois la boucle terminée, on affecte à result la valeur de n qui est le PGCD des deux nombres.

Dans l'exemple `gcd(9,6)` :
1. n = 9, m = 6 
2. n = 6, m = 3
3. n = 3, m = 0
4. return 3.

## Exercice 2
Implémentez une manière de calculer $x^n$ en utilisant la méthode de dichotomie.

In [27]:
def powdi(x: int, n: int):
    # A COMPLETER
    if n == 0:
        return 1
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n/2) * powdi(x, n/2)
    if n % 2 != 0:
        return x * powdi(x, n//2) * powdi(x, n//2)
    return None

In [28]:
assert powdi(2,3) == 8
assert powdi(4,2) == 16
assert powdi(2,2) == 4
assert powdi(4,0) == 1
assert powdi(2,1) == 2
assert not powdi(5,2) == 10
assert not powdi(3,7) == 10
assert not powdi(3,3) == 10

### Explications (Premier paragraphe parlant d'un cas concret fait par Gobi, et le reste par Mathias)

Pour expliquer ce qui se passe dans ce code, j'aime commencer par un exemple concret. Prenons `powdi(2, 8)`.
1. `n=8` est pair, donc on a `2^8 = powdi(2, 4) * powdi(2, 4)`
2. `n=4` est pair, donc on a `2^4 = powdi(2, 2) * powdi(2, 2)`.    
3. `n=2` est pair, donc on a `2^2 = powdi(2, 1) * powdi(2, 1)`.
4. `n=1` est impair, donc on retourne 2 (la base). Et donc `powdi(2,1) = 2`.
5. Donc `powdi(2, 2) = 2 * 2 = 4`.
6. Donc `powdi(2, 4) = 4 * 4 = 16`.
7. Donc `powdi(2, 8) = 16 * 16 = 256`.
8. Donc `2^8 = 256`.
9. On retourne 256.

L'algorithme de dichotomie pour le calcul de la puissance d'un nombre repose sur le fait que si `n` est pair, alors `x^n = x^(n/2) * x^(n/2)`. Si `n` est impair, alors `x^n = x * x^(n//2) * x^(n//2)`. On répète cette opération jusqu'à ce que `n` soit égal à 0 ou 1. Si `n` est égal à 0, on retourne 1. Si `n` est égal à 1, on retourne `x`. Sinon, on applique la formule récursive pour calculer `x^n`.

## Exercice 3
La suite de Fibonacci est une suite de nombres entiers dans laquelle chaque nombre $f_{n+2}$ correspond à la somme des deux nombres qui le précèdent, $f_{n+1}+f_{n}$.

Implémentez l'algorithme de Fibonacci en utilisant la multiplication matricielle.

In [35]:
import numpy as np

def fibo(n: int):
    f0f1 = np.array([[0],[1]])
    # A COMPLETER
    A = np.array([[0,1],
                  [1,1]])
    Apower_n = np.linalg.matrix_power(A, n) # utiliser powdi est preferable !!!
    print(Apower_n)
    return (Apower_n @ f0f1)[0] 

In [36]:
fibo(9)

[[21 34]
 [34 55]]


array([34])

In [13]:
def powdi(x: int, n: int):
    # A COMPLETER
    if n == 0:
        return np.identity(2)
    if n == 1:
        return x
    if n % 2 == 0:
        return powdi(x, n/2) @ powdi(x, n/2)
    if n % 2 != 0:
        return x @ powdi(x, n//2) @ powdi(x, n//2)
    return None

In [14]:
powdi(np.array([[0,1],[1,1]]), 8)

array([[13, 21],
       [21, 34]])

In [ ]:
assert fibo(8) == 21
assert fibo(10) == 55
assert fibo(0) == 0
assert fibo(1) == 1
assert not fibo(5) == 10

[[13 21]
 [21 34]]
[[34 55]
 [55 89]]
[[1 0]
 [0 1]]
[[0 1]
 [1 1]]
[[3 5]
 [5 8]]


### Explications (50% Gobi,  et 50% Mathias, ici est fait fifty-fifty)

Pour expliquer ce qui se passe dans ce code, j'aime commencer par un exemple concret. Prenons `fibo(8)`.
1. On commence avec la matrice `f0f1 = [[0], [1]]` qui représente les valeurs initiales de la suite de Fibonacci.
2. On définit la matrice `A = [[0, 1], [1, 1]]` qui permet de passer d'un élément de la suite au suivant.
3. On calcule la matrice `Apower_n = A^n` en utilisant la fonction `np.linalg.matrix_power(A, n)` de numpy pour obtenir la matrice `A` élevée à la puissance `n`. Save time.
4. On multiplie ensuite cette matrice `Apower_n` par le vecteur `f0f1` à l'aide de l'opérateur `@` (multiplication matricielle) pour obtenir le \(n\)-ième terme de la suite de Fibonacci. Le résultat de cette multiplication est un vecteur, et nous récupérons la première entrée du vecteur, c'est-à-dire `[0]`, qui correspond à \( F(n) \), le \(n\)-ième terme de la suite de Fibonacci.
5. La fonction retourne cette première valeur, qui est le terme \( F(n) \) de la suite de Fibonacci.

### Étapes de l'exécution pour `fibo(8)`

1. **Initialisation** :
   - La matrice initiale est `f0f1 = [[0], [1]]`, qui représente $( F(0) = 0 )$ et $( F(1) = 1 $).

2. **Définition de la matrice $( A )$** :
   - La matrice de transition $( A )$ est définie comme suit :
   $[
   A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
   ]$
   Cette matrice est utilisée pour calculer la suite de Fibonacci, car elle modélise la relation de récurrence $( F(n) = F(n-1) + F(n-2) )$.

3. **Calcul de la puissance de la matrice $( A^n )$** :
   - La fonction `np.linalg.matrix_power(A, n)` calcule $( A^n )$, où $( n = 8 )$ dans notre cas. Pour $( n = 8 )$, cela revient à multiplier la matrice $( A )$ par elle-même 8 fois.
   - Le résultat de $( A^8 )$ est :
   $[
   A^8 = \begin{pmatrix} 13 & 21 \\ 21 & 34 \end{pmatrix}
   ]$
   On remaruque que Chaque élément de cette matrice par exemple contient des termes de Fibonacci. Par exemple, le $( 13 )$ correspond à $( F(7) )$ et le $( 21 )$ correspond à $( F(8) )$.

4. **Multiplication matricielle** :
   - On effectue ensuite la multiplication de $( A^n )$ avec le vecteur initial `f0f1` :
   $[
   \begin{pmatrix} 13 & 21 \\ 21 & 34 \end{pmatrix} \times \begin{pmatrix} 0 \\ 1 \end{pmatrix} = \begin{pmatrix} 21 \\ 34 \end{pmatrix}
   ]$
   Cette multiplication donne le vecteur $( \begin{pmatrix} F(8) \\ F(9) \end{pmatrix} )$, où $( F(8) = 21 )$ et $( F(9) = 34 )$.

5. **Résultat** :
   - La fonction retourne la première valeur du vecteur résultant, c'est-à-dire $( F(8) = 21 )$.



### Exercice 3.1 (50% Gobi,  et 50% Mathias)
$(1)$ Montrez qu'il existe une matrice $A$ reliant $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ à $\left[\begin{array}{c}
f_{n+1} \\
f_{n+2}
\end{array}\right]$ pour tout $n\in \mathbb{N}$.

$(2)$ Trouvez alors une expression de $\left[\begin{array}{c}
f_n \\
f_{n+1}
\end{array}\right]$ selon $A$ et  $\left[\begin{array}{c}
f_0 \\
f_{1}
\end{array}\right]$ .


$(1)$ Démontrez qu'il existe une matrice $A$ reliant 
$$
\begin{pmatrix}
f_n \\
f_{n+1}
\end{pmatrix}
$$
à 
$$
\begin{pmatrix}
f_{n+1} \\
f_{n+2}
\end{pmatrix}
$$
pour tout $n \in \mathbb{N}$.

**Solution :** 

Nous savons que la suite de Fibonacci est définie par la relation de récurrence :
$$
f_{n+2} = f_{n+1} + f_n
$$
Cela signifie que nous pouvons exprimer le vecteur 
$$
\begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}
$$
comme une combinaison linéaire du vecteur 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
à l'aide de la matrice suivante :
$$
A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
$$
En effet, en appliquant cette matrice à 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
nous obtenons :
$$
A \cdot \begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix} = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix} \cdot \begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix} = \begin{pmatrix} f_{n+1} \\ f_n + f_{n+1} \end{pmatrix} = \begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}
$$

Cela prouve qu'il existe bien une matrice $A$ reliant 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
à 
$$
\begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}
$$
pour tout $n \in \mathbb{N}$.

$(2)$ Exprimez alors 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
selon $A$ et 
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix}.
$$

**Solution :** 

Nous savons que la matrice $A$ permet de relier deux vecteurs consécutifs de la suite de Fibonacci. Par conséquent, pour exprimer 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
en fonction de 
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix}
$$
il suffit de multiplier la matrice $A$ de manière itérative $n$ fois :
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix} = A^n \cdot \begin{pmatrix} f_0 \\ f_1 \end{pmatrix}
$$
où
$$
A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
$$
et
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$$

Ainsi, pour un entier $n$, nous pouvons obtenir le vecteur 
$$
\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}
$$
en appliquant $A^n$ au vecteur initial 
$$
\begin{pmatrix} f_0 \\ f_1 \end{pmatrix}
$$


### Exercice 3.2 - (<font color='#db60cf'>Bonus</font>) Une formule analytique pour $f_n$
Que peut-on dire de $A$ ? Déterminez ses valeurs propres et ses sous-espaces propres associés.

**Contribution: We did it together as well**



Considérons la matrice $A$ suivante :
$$
A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
$$

#### On peut dire de $A$ qu'elle possède les propriétés suivantes:

1. **Symétrie :** La matrice $A$ est symétrique, car $A = A^T$.

2. **Orthogonalité :** La matrice $A$ n'est pas orthogonale, car $A^T A \neq I$.

3. **Caractère de transformation :** La matrice $A$ est utilisée dans les calculs de la suite de Fibonacci pour transformer les vecteurs de la suite. Elle permet de passer d'un vecteur de la forme $\begin{pmatrix} f_n \\ f_{n+1} \end{pmatrix}$ à un vecteur $\begin{pmatrix} f_{n+1} \\ f_{n+2} \end{pmatrix}$ en appliquant la matrice.

4. **Type de matrice :** Elle est également une matrice inversible, car son déterminant est non nul $(-1)$.

#### Valeurs propres et sous-espaces propres

Pour déterminer les valeurs propres de $A$, nous devons résoudre le polynôme caractéristique :
$$
\text{det}(A - \lambda I) = 0
$$
où $I$ est la matrice identité et $\lambda$ représente les valeurs propres.

Calculons $A - \lambda I$ :
$$
A - \lambda I = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix} - \lambda \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} = \begin{pmatrix} -\lambda & 1 \\ 1 & 1 - \lambda \end{pmatrix}
$$

Le polynôme caractéristique est :
$$
\text{det}(A - \lambda I) = \text{det}\begin{pmatrix} -\lambda & 1 \\ 1 & 1 - \lambda \end{pmatrix}
$$
Calculons le déterminant :
$$
\text{det}(A - \lambda I) = (-\lambda) \cdot (1 - \lambda) - (1 \cdot 1) = -\lambda + \lambda^2 - 1
$$
$$
= \lambda^2 - \lambda - 1
$$

Les valeurs propres sont les racines du polynôme caractéristique :
$$
\lambda^2 - \lambda - 1 = 0
$$

Résolvons cette équation quadratique :
$$
\lambda = \frac{1 \pm \sqrt{1 + 4}}{2} = \frac{1 \pm \sqrt{5}}{2}
$$

Les valeurs propres sont :
$$
\lambda_1 = \frac{1 + \sqrt{5}}{2} \quad \text{et} \quad \lambda_2 = \frac{1 - \sqrt{5}}{2}
$$

Pour chaque valeur propre, trouvons les sous-espaces propres associés. 

### Calcul des sous-espaces propres

Un **sous-espace propre** associé à une valeur propre $ \lambda $ est l'ensemble des vecteurs non nuls $ v $ qui satisfont l'équation suivante :

$ A v = \lambda v $

Pour chaque valeur propre $ \lambda $, nous devons résoudre le système d'équations :

$ (A - \lambda I) v = 0 $

où $ I $ est la matrice identité et $ v $ est un vecteur propre.

### Étape 1 : Résolution pour $ \lambda_1 = \frac{1 + \sqrt{5}}{2} $

1. **Calcul de $ A - \lambda_1 I $** :
   
$ A - \lambda_1 I = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix} - \frac{1 + \sqrt{5}}{2} \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} = \begin{pmatrix} -\frac{1 + \sqrt{5}}{2} & 1 \\ 1 & 1 - \frac{1 + \sqrt{5}}{2} \end{pmatrix} $

2. **Système d'équations** :

Le système à résoudre est :

$ ( A - \lambda_1 I ) v = 0 $

Résolvant ce système, nous trouverons les vecteurs propres associés à $ \lambda_1 $ et on a pour tout calcul bien fait:
   $$
   \mathbf{v}_1 = \begin{pmatrix} 1 \\ \frac{1 + \sqrt{5}}{2} \end{pmatrix}
   $$

### Étape 2 : Résolution pour $ \lambda_2 = \frac{1 - \sqrt{5}}{2} $

1. **Calcul de $ A - \lambda_2 I $** :

$ A - \lambda_2 I = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix} - \frac{1 - \sqrt{5}}{2} \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} = \begin{pmatrix} -\frac{1 - \sqrt{5}}{2} & 1 \\ 1 & 1 - \frac{1 - \sqrt{5}}{2} \end{pmatrix} $

2. **Système d'équations** :

Le système à résoudre est :

$ ( A - \lambda_2 I ) v = 0 $

Résolvant ce système, on trouvera les vecteurs propres associés à $ \lambda_2 $ et on a pour tout calcul bien fait:

  $$
   \mathbf{v}_2 = \begin{pmatrix} 1 \\ \frac{1 - \sqrt{5}}{2} \end{pmatrix}
   $$
Eh donc: 
- Le sous-espace propre associé à $ \lambda_1 $ est engendré par $ v_1 $.
- Le sous-espace propre associé à $ \lambda_2 $ est engendré par $ v_2 $.



En utilisant $(2)$, en déduire une forme analytique de $f_n$.

Pour exprimer 
$$
\begin{pmatrix}
f_n \\
f_{n+1}
\end{pmatrix}
$$
en termes de $A$ et 
$$
\begin{pmatrix}
f_0 \\
f_1
\end{pmatrix}
$$
nous avons :
$$
\begin{pmatrix}
f_n \\
f_{n+1}
\end{pmatrix}
= A^n \cdot \begin{pmatrix}
f_0 \\
f_1
\end{pmatrix}
$$

Allons étape par étape pour effectuer les calcules:

### Étape 1 : Définir les termes initiaux
Les premiers termes de la suite de Fibonacci sont $ f_0 = 0 $ et $ f_1 = 1 $, donc le vecteur initial est :
$$
\begin{pmatrix}
f_0 \\
f_1
\end{pmatrix} = \begin{pmatrix}
0 \\
1
\end{pmatrix}
$$

### Étape 2 : Diagonaliser la matrice $ A $
La matrice $ A $ est :
$$
A = \begin{pmatrix}
0 & 1 \\
1 & 1
\end{pmatrix}
$$
Nous l'avons diagonalée avec :
$$
A = P D P^{-1}
$$
où :
$$
P = \begin{pmatrix}
1 & 1 \\
\frac{1 + \sqrt{5}}{2} & \frac{1 - \sqrt{5}}{2}
\end{pmatrix}
$$
et la matrice diagonale des valeurs propres est :
$$
D = \begin{pmatrix}
\lambda_1 & 0 \\
0 & \lambda_2
\end{pmatrix}
= \begin{pmatrix}
\frac{1 + \sqrt{5}}{2} & 0 \\
0 & \frac{1 - \sqrt{5}}{2}
\end{pmatrix}
$$

### Étape 3 : Calcul de $ A^n $
Maintenant, nous allons calculer $ A^n $ en utilisant la diagonalisation :
$$
A^n = P D^n P^{-1}
$$
Où :
$$
D^n = \begin{pmatrix}
\lambda_1^n & 0 \\
0 & \lambda_2^n
\end{pmatrix}
$$
Ainsi, nous avons :
$$
A^n = P \begin{pmatrix}
\lambda_1^n & 0 \\
0 & \lambda_2^n
\end{pmatrix} P^{-1}
$$

### Étape 4 : Appliquer à $ \begin{pmatrix} f_0 \\ f_1 \end{pmatrix} $
Maintenant, appliquons $ A^n $ au vecteur initial $ \begin{pmatrix} f_0 \\ f_1 \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \end{pmatrix} $.

Premièrement, calculons :
$$
P^{-1} = \frac{1}{\sqrt{5}} \begin{pmatrix}
\frac{1 - \sqrt{5}}{2} & -1 \\
-\frac{1 + \sqrt{5}}{2} & 1
\end{pmatrix}
$$
Puis :
$$
P^{-1} \begin{pmatrix} 0 \\ 1 \end{pmatrix} = \frac{1}{\sqrt{5}} \begin{pmatrix}
-1 \\
1
\end{pmatrix}
$$

En multipliant par $ D^n $, nous obtenons :
$$
\begin{pmatrix}
\lambda_1^n & 0 \\
0 & \lambda_2^n
\end{pmatrix} \cdot \frac{1}{\sqrt{5}} \begin{pmatrix}
-1 \\
1
\end{pmatrix} = \frac{1}{\sqrt{5}} \begin{pmatrix}
-\lambda_1^n \\
\lambda_2^n
\end{pmatrix}
$$

Enfin, multiplions par $ P $ :
$$
P \cdot \frac{1}{\sqrt{5}} \begin{pmatrix}
-\lambda_1^n \\
\lambda_2^n
\end{pmatrix} = \frac{1}{\sqrt{5}} \begin{pmatrix}
\lambda_2^n - \lambda_1^n \\
\frac{1 + \sqrt{5}}{2} \lambda_2^n - \frac{1 - \sqrt{5}}{2} \lambda_1^n
\end{pmatrix}
$$

Le premier élément de ce vecteur est le terme $ f_n $ de la suite de Fibonacci, donc :
$$
f_n = \frac{1}{\sqrt{5}} \left( \lambda_1^n - \lambda_2^n \right)
$$
où $ \lambda_1 = \frac{1 + \sqrt{5}}{2} $ et $ \lambda_2 = \frac{1 - \sqrt{5}}{2} $.

### Eh donc:
La **formule explicite** pour le $ n $-ème terme de la suite de Fibonacci est donc donnée par :
$$
f_n = \frac{1}{\sqrt{5}} \left( \left( \frac{1 + \sqrt{5}}{2} \right)^n - \left( \frac{1 - \sqrt{5}}{2} \right)^n \right)
$$



## Exercice 4 
Implémentez et testez les 3 versions de l'algorithme calculant la sous-suite de somme maximale, c'est-à-dire:
* 3 boucles imbriquées
* 2 boucles imbriquées
* une seule boucle (Kadane)

In [2]:
def maxSub3(m):
    maxSum = 0 # initialiser la somme maximale à 0
    n = len(m) # obtenir la taille de la liste
    for i in range(n): # parcourir la liste
        for j in range(i, n): # parcourir la liste à partir de l'indice i
            currentSum = 0 # initialiser la somme courante à 0
            for k in range(i, j+1): # parcourir la liste de i à j
                currentSum += m[k] # ajouter l'élément k à la somme courante
            maxSum = max(maxSum, currentSum) # mettre à jour la somme maximale
    return maxSum

def maxSub2(m):
    maxSum = 0 # initialiser la somme maximale à 0
    n = len(m) # obtenir la taille de la liste
    for i in range(n):  # parcourir la liste
        currentSum = 0 # initialiser la somme courante à 0
        for j in range(i, n):  # parcourir la liste à partir de l'indice i
            currentSum += m[j] # ajouter l'élément j à la somme courante
            maxSum = max(maxSum, currentSum) # mettre à jour la somme maximale
    return maxSum

def maxSub1(m):
    maxSum = 0
    currentSum = 0

    for x in m:  # Boucle unique pour parcourir les éléments
        currentSum = max(x, currentSum + x) # Mettre à jour la somme courante
        maxSum = max(maxSum, currentSum) # Mettre à jour la somme maximale and everything is done in one loop
    return maxSum

In [3]:
assert maxSub3([4,3,-10,2]) == 7
assert maxSub3([4,3,-10,2,8]) == 10
assert not maxSub3([4,3,-10,2,8]) == -10

assert maxSub2([4,3,-10,2]) == 7
assert maxSub2([4,3,-10,2,8]) == 10
assert not maxSub2([4,3,-10,2,8]) == -10

assert maxSub1([4,3,-10,2]) == 7
assert maxSub1([4,3,-10,2,8]) == 10
assert not maxSub1([4,3,-10,2,8]) == -10

### Explications (Gobi(maxSub2, maxSub)  et  Mathias (maxSub3))

1. **`maxSub3(m)`** :
   - Utilise trois boucles imbriquées. La somme des sous-suites est calculée avec une boucle interne, en ajoutant chaque élément de la sous-suite à `currentSum`. Ensuite, `maxSum` est mis à jour si `currentSum` est plus grand.

2. **`maxSub2(m)`** :
   - Utilise deux boucles imbriquées. La première boucle fixe le début de la sous-suite. La seconde boucle calcule la somme de la sous-suite en ajoutant successivement les éléments. `maxSum` est mis à jour pour chaque sous-suite.

3. **`maxSub1(m)`** :
   - Utilise l'algorithme de Kadane avec une seule boucle. La variable `currentSum` maintient la somme de la sous-suite courante, et `maxSum` est mis à jour si `currentSum` est plus grand.

Prenons l'exemple `[-1, 2, 5, 1]` en testant avec le premier maxSub3  car le cheminement est le même pour les trois fonctions. Voici comment ça marche avec trois boucles imbriquées :

### Tableau : `[-1, 2, 5, 1]`

1. **Boucle externe (i)** : Sélectionne le point de départ de la sous-séquence.
2. **Boucle intermédiaire (j)** : Sélectionne le point de fin de la sous-séquence.
3. **Boucle interne (k)** : Calcule la somme de tous les éléments entre les indices \( i \) et \( j \).

### Étape par étape :

1. **i = 0 (on commence au premier élément -1)** :
    - j = 0 → sous-séquence : `[-1]` → somme = -1
    - j = 1 → sous-séquence : `[-1, 2]` → somme = 1
    - j = 2 → sous-séquence : `[-1, 2, 5]` → somme = 6
    - j = 3 → sous-séquence : `[-1, 2, 5, 1]` → somme = 7 (nouveau max)

2. **i = 1 (on commence au deuxième élément 2)** :
    - j = 1 → sous-séquence : `[2]` → somme = 2
    - j = 2 → sous-séquence : `[2, 5]` → somme = 7 (max reste 7)
    - j = 3 → sous-séquence : `[2, 5, 1]` → somme = 8 (nouveau max)

3. **i = 2 (on commence au troisième élément 5)** :
    - j = 2 → sous-séquence : `[5]` → somme = 5
    - j = 3 → sous-séquence : `[5, 1]` → somme = 6

4. **i = 3 (on commence au dernier élément 1)** :
    - j = 3 → sous-séquence : `[1]` → somme = 1

### Conclusion :

Le maxSum final est 8, qui correspond à la sous-séquence `[2, 5, 1]`.